[rewrite_local]
^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(collectCoupon|receiveCoupon|getCoupon|newReceiveCoupon) url script-request-body https://raw.githubusercontent.com/shuiseliuli/jd-coupon-qx/main/jd_coupon_capture.js
^https:\/\/coupon\.jd\.com\/coupon\/couponReceive url script-request-body https://raw.githubusercontent.com/shuiseliuli/jd-coupon-qx/main/jd_coupon_capture.js
