; 京东抢券抓包规则
; 手动领一次券即可抓到，抓到后请关闭此规则
hostname = api.m.jd.com, coupon.jd.com, api.jd.com
^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(collectCoupon|receiveCoupon|getCoupon|newReceiveCoupon) url script-request-body https://raw.githubusercontent.com/shuiseliuli/jd-coupon-qx/main/jd_coupon_capture.js
^https:\/\/coupon\.jd\.com\/coupon\/couponReceive url script-request-body https://raw.githubusercontent.com/shuiseliuli/jd-coupon-qx/main/jd_coupon_capture.js
